2019-01-26 14:50:56,180 ERROR: Exception on /admin/user [POST] [in /home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/md_length/app/admin/routes.py", line 36, in add_user
    json_obj = json.loads(request.args.get('form_json'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
2019-01-26 14:51:18,361 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 14:51:35,837 ERROR: Exception on /admin/user [POST] [in /home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/md_length/app/admin/routes.py", line 36, in add_user
    json_obj = json.loads(request.args.get('form_json'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
2019-01-26 14:52:01,714 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 14:55:55,789 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 14:57:07,747 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 14:57:45,555 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 14:58:50,661 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 14:59:26,970 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:05:07,266 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:07:31,084 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:22:19,462 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:22:50,110 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:24:15,753 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:28:01,476 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:29:02,575 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:29:44,361 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:31:34,083 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:34:47,920 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:35:07,832 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:35:51,571 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:36:49,449 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:37:39,399 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:43:13,735 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:44:29,554 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:44:58,016 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:45:50,619 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:48:06,749 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:54:35,838 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:58:14,184 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 15:59:19,316 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 16:00:28,273 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 20:54:35,669 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 20:56:13,080 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 20:56:21,089 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 21:13:15,864 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
2019-01-26 21:13:22,802 ERROR: Exception on / [GET] [in /home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/holger/git/md_length/app/main/routes.py", line 14, in index
    return render_template('index.html')
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/holger/git/md_length/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/holger/git/md_length/app/templates/base.html", line 191, in top-level template code
    <a href="{{ url_for('admin.get_instrument_list') }}"><i class="fas fa-cogs"></i> Instruments</a>
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/holger/git/md_length/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'admin.get_instrument_list'. Did you mean 'admin.get_department_list' instead?
2019-01-26 21:21:41,010 INFO: Length dep. server startup [in /home/holger/git/md_length/app/__init__.py:73]
