2019-01-10 17:16:08,605 ERROR: Exception on / [GET] [in c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\holger\Documents\git\proto_qry\app\main\routes.py", line 19, in index
    files=data_list, title='Home')
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\holger\Documents\git\proto_qry\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\holger\Documents\git\proto_qry\app\templates\base.html", line 15, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Users\holger\Documents\git\proto_qry\app\templates\index.html", line 19, in block "app_content"
    {% for i, col_header in enumerate(table_header) %}
jinja2.exceptions.UndefinedError: 'enumerate' is undefined
2019-01-10 17:17:45,481 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\proto_qry\app\__init__.py:48]
2019-01-10 17:18:28,663 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\proto_qry\app\__init__.py:48]
2019-01-10 17:19:20,049 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\proto_qry\app\__init__.py:48]
2019-01-10 17:20:04,541 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\proto_qry\app\__init__.py:48]
2019-01-10 17:20:06,195 ERROR: Exception on / [GET] [in c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\holger\Documents\git\proto_qry\app\main\routes.py", line 17, in index
    files=data_list, title='Home')
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\holger\Documents\git\proto_qry\app\templates\index.html", line 19, in template
    {{ row = loop.index }}
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 199, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "c:\users\holger\documents\git\proto_qry\venv\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2019-01-10 17:20:36,771 INFO: Protocol data qry server startup [in C:\Users\holger\Documents\git\proto_qry\app\__init__.py:48]
